#25638: ForeversCreationWizard - persist steps data after page reload
BudsiesApp/vsf-capybara pull request #103
Opened 2022-01-25 09:18 UTC by soarer1004

2022-01-26 17:09 UTC, gorbunovav requested changes

2022-01-26 17:09 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +              @input-field-blur="onPetInfoStepInputFieldBlur"
а мы не можем тут тоже просто при изменении наднных сохранение выполнять?

2022-01-26 17:09 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +        }
Ты же его в mounted создаешь - т.е. тут он уже должен быть, если нет - то это exception. Зачем создание многократно дублировать?

Вообще наверное эту зависимость можно оформить точно также, как StorageManager реализован - через экспорт константы в модуле 🤔

2022-01-26 17:09 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +      this.currentStep = 1;
Если мы хотим, чтобы при перезагрузке страницы пользователь оставался на той же вкладке, где и был - то возможно логичнее просто сохранять номер активной вкладки вместе с остальными данными?

Другой ваирант - добавить вкладу в url

2022-01-26 17:09 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +      }
У нас получается есть еще метод `fillPlushieData` (видимо стоит переименовать - он же специлизированный для cartItem и теперь их два).

Они вызываются из немного разных мест сейчас.

Я бы наверное вынес логику определения того, какой из них дергать в место их вызыова. 
Сейчас получается оба метода выываются всегда и внутри каждого проверяется нужно ли выполнять действия - мне кажется это отдельная ответственность.

2022-01-26 17:09 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +      }
возможно эти проверки лучше тоже в месте вызова делать 🤔

2022-01-27 05:51 UTC, soarer1004 commented on components/organisms/o-forevers-creation-wizard.vue
> +              @input-field-blur="onPetInfoStepInputFieldBlur"
Можем, так сделал чтобы на каждое событие ввода не обращаться к localStorage

2022-01-27 05:55 UTC, soarer1004 commented
@gorbunovav Возможно стоит очищать все данные о состоянии кастомайзера после добавления продукта в корзину? Чтобы не забивать этим состоянием LS. И тогда можно будет сохранять не только sku продукта, а весь продукт целиком. И тогда не нужно будет ждать пока продукт загрузится.

2022-01-27 10:13 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +              @input-field-blur="onPetInfoStepInputFieldBlur"
@soarer1004 мне кажется не страшно, если постоянно сохраняться будет (по крайней мере если визуально это никак проявляться не будет 🤔)

Зато меньше дополнительной логики

2022-01-27 10:25 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +      }
может тогда надо и fillPlushieDataFromCartItem вызывать? 🤔

2022-01-27 10:27 UTC, gorbunovav commented
@soarer1004 мне кажется product в localStorage лучше не хранить, т.к. он в процессе разработки может поменяться, в т.ч. по структуре и весрия в storage будет не совместима с нашим кодом.

2022-01-28 12:27 UTC, gorbunovav approved these changes

2022-01-28 12:27 UTC, merged