#25815: Fix cart items duplication on quantity updating
BudsiesApp/vsf-capybara pull request #106
Opened 2022-01-26 09:32 UTC by soarer1004

2022-01-26 11:09 UTC, gorbunovav requested changes

2022-01-26 11:09 UTC, gorbunovav commented on pages/DetailedCart.vue
> +    this.syncQuantity = debounce(this.syncQuantity, CHANGE_QUANTITY_DEBOUNCE_TIME);
Ты получается переопределяешь существующий метод и меняешь его поведение - мне кажется так лучше не делать, т.к. это не очевидно при просмотре кода исходного метода и его вызовов.

Лучше debounced-версию сохранить отдельно 🤔

2022-01-26 11:09 UTC, gorbunovav commented on pages/DetailedCart.vue
> +      });
а можешь в задаче описать причины почему `updateQuantity` решил заменить на `cart/sync`?

2022-01-27 06:43 UTC, soarer1004 commented on pages/DetailedCart.vue
> +      });
@gorbunovav Описал причины - https://redmine.optimuspro.ru/issues/25638#Update . Но в целом это сделано потому что логика обновления qty на клиенте и синхронизация разделены, т.к. в debounce нам нужно только синхронизацию обернуть. А `cart/updateQuantity` будет повторно вызывать мутацию на обновление qty. Поэтому нам тут достаточно использовать синхронизацию напрямую

2022-01-27 10:08 UTC, gorbunovav approved these changes

2022-01-27 10:08 UTC, merged