#26277: Felted Magnets
BudsiesApp/vsf-capybara pull request #150
Opened 2022-04-20 07:25 UTC by soarer1004

2022-04-20 14:17 UTC, gorbunovav requested changes

2022-04-20 14:17 UTC, gorbunovav commented on pages/PrintedProduct.vue
> +      }
Мне кажется можно не заморачиваться с проверкой продукта 🤔

2022-04-20 14:17 UTC, gorbunovav commented on pages/PrintedProduct.vue
> +      :is-felted-magnet="isFeltedMagnet"
в принципе мы продукт внутрь передаем уже - можно внутри и проверить felted это или нет 🤔

2022-04-20 14:17 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +              />
там в итоге дополнительные две фотки сделали не обязательными

2022-04-21 02:45 UTC, soarer1004 commented on pages/PrintedProduct.vue
> +      :is-felted-magnet="isFeltedMagnet"
Сделал через props чтобы не дублировать вычисляемое свойство в компоненте формы. Но если убрать проверку в `loadData`, тогда в `PrintedProduct` это свойство не нужно. Переделал на вычисляемое свойство в компоненте формы

2022-04-21 03:13 UTC, soarer1004 commented on components/organisms/o-printed-product-order-form.vue
> +              />
Тут проблема получается - если добавить "Back View" изображение, а "Front View" не добавлять, то при редактировании продукта после добавления в корзину - изображение отображается в "Front View". Это не критично?

2022-04-21 09:17 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +              />
@soarer1004 пока наверное не критично 🤔 но хорошо, что заметил 👍

2022-04-21 10:06 UTC, gorbunovav approved these changes

2022-04-21 10:07 UTC, merged