#27010: Forevers Creation Wizard - allow to pre-select product & size via url
BudsiesApp/vsf-capybara pull request #188
Opened 2022-08-03 09:03 UTC by soarer1004

2022-08-04 12:18 UTC, gorbunovav requested changes

2022-08-04 12:18 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
>      }
возможно тут тоже надо возврат вставить? наверное мы не хотим что то еще заполнять, если у нас уже есть plushie?

2022-08-04 12:18 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +      }
а почему мы тут не падаем? 🤔

и в целом есть ли смысл в использовании `this.preselectedProductType` в качестве дефолта?
вроде бы в двух местах, где вызывается `getProductType` plushie уже должен быть загружен к моменту вызова 🤔

2022-08-05 02:52 UTC, soarer1004 commented on components/organisms/o-forevers-creation-wizard.vue
>      }
Дальше по коду есть заполнение размера, так что в этом случае тут не нужен возврат. Размер может заполняться и для существующего plushie.

2022-08-05 03:28 UTC, soarer1004 commented on components/organisms/o-forevers-creation-wizard.vue
> +      }
Ну тут вызывающий код ожидает, что метод вернет строку или undefined, а не упадет с ошибкой. Если тут падать, тогда нужно будет в вызывающем коде ошибку ловить. Да, `preselectedProductType` наверное нет смысла использовать по умолчанию.

2022-08-05 10:17 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +      }
@soarer1004 так а это же исключительная ситуация получается - неожидаемый тип продукта.
Продукт приходит не из пользовательского ввода.
Т.е. по нашей идеологии мы должны падать, а не глушить ошибку.

2022-08-05 10:18 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
>      }
@soarer1004 а в каких случаях размер нужно заполнять для сущетсвующего plushie? 🤔

2022-08-05 10:20 UTC, soarer1004 commented on components/organisms/o-forevers-creation-wizard.vue
>      }
@gorbunovav например, если пользователь перешел по ссылке с предзаполненным размером и после создания plushie перезагрузил страницу

2022-08-05 10:35 UTC, soarer1004 commented on components/organisms/o-forevers-creation-wizard.vue
> +      }
@gorbunovav исправил

2022-08-05 10:44 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
>      }
@soarer1004 ок. Тогда возможно `fillProductTypeStepDataByPreselectedParam` не нужно в этом случае вызывать?
кстати - получается, что мы добавили в создание plushie в компонент `o-forevers-creation-wizard`, а до этого оно было только в самом шаге.
Возможно стоит оставить реализацию только в одном месте 🤔
(как вариант - вызывать метод самого шага - чтобы автоматом сопутствующие события вызывались 🤔)

2022-08-05 11:02 UTC, soarer1004 commented on components/organisms/o-forevers-creation-wizard.vue
>      }
@gorbunovav Внутри `fillProductTypeStepDataByPreselectedParam` есть проверка на текущий продукт. Но думаю да, можно избавиться от этого метода и вызывать метод шага. Но это будет работать только если этот шаг активен(Т.к. SfSteps использует v-if для отображения шагов. Т.е. на другом шаге этот метод будет недоступен). Хотя вроде не может быть такого, что нам нужно создать plushie если активен другой шаг

2022-08-05 11:37 UTC, soarer1004 commented on components/organisms/o-forevers-creation-wizard.vue
>      }
@gorbunovav Возможно будет лучше сделать `create-plushie` миксин и использовать его для создания plushie в обоих компонентах. Иначе получается, что родительский компонент зависит от дочернего, что странно

2022-08-08 18:13 UTC, gorbunovav requested changes

2022-08-08 18:13 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +              @type-choose="onProductTypeChoose"
а ты же получается выпилил там и `input` и `next-step` в шаге

2022-08-08 18:13 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
>      }
@soarer1004 извини, забыл на выходных отписаться.

Мне кажется mixin тут не очень подходит (т.к. речь только об одном методе и нам не нужно обеспечивать сходность поведения двух компонентов).
Логичнее, видимо, разместить просто метод в одном из компонентов.

Чтобы не создавать зависимость родительского компонента от дочернего можно реализовать метод в роидтельском, а в шаг передавать его в качестве property 🤔

2022-08-09 16:22 UTC, merged