#27456: Adjust menus, footer and the cart page
BudsiesApp/vsf-capybara pull request #206
Opened 2022-10-03 05:02 UTC by soarer1004

2022-10-06 13:36 UTC, gorbunovav requested changes

2022-10-06 13:36 UTC, gorbunovav commented on components/organisms/o-header.vue
> +            />
@soarer1004  что то я тут не понял - `MMenu` - это получается конкретное подменю со статическим набором ссылок.

В petsies-варианте оно выводилось для одного пункта главного меню.

Тут же оно вставляется в цикле, при этом оно работает только потому, что тут только один пункт с подменю.
Перечисленные в данных этого компонента под-пукнты, насколько я понимаю, не используются

2022-10-07 07:57 UTC, soarer1004 commented on components/organisms/o-header.vue
> +            />
@gorbunovav Извиняюсь, осталась от прошлого варианта логика. Переделал и удалил неиспользуемый код

2022-10-07 10:34 UTC, gorbunovav approved these changes

2022-10-07 10:34 UTC, merged