#27574: Bobblehead and Figurines creation pages
BudsiesApp/vsf-capybara pull request #230
Opened 2022-12-27 14:32 UTC by soarer1004

2022-12-29 12:11 UTC, gorbunovav requested changes

2022-12-29 12:11 UTC, gorbunovav commented on components/organisms/o-base-plushie-product-order-form.vue
> +        <p>{{ $t('All quantity discounts applied automatically at checkout:') }}</p>
Мне кажется контент popup'ов динамический в Magento - получается из static block'ов

2022-12-29 12:11 UTC, gorbunovav commented on components/organisms/o-base-plushie-product-order-form.vue
> +  <div class="o-base-plushie-product-order-form">
"base" слишком общее название - она же по факту только для двух продуктов пока и есть несколько других вариантов форм для других продуктов.

Давай назовем пока "clay-product-....".

Я добавлю задачу по унификации форм создания - попроубем может в миксин часть логики вынести.

2022-12-29 13:06 UTC, gorbunovav commented on pages/BasePlushieProduct.vue
> +      await this.loadPlushieData();
получается тонкий момент есть - `sku` может поменяться, но при этом может присутствовать `existingPlushieId` и тогда продукт будет не соответствовать продукту в plushie

2022-12-30 05:18 UTC, soarer1004 commented on pages/BasePlushieProduct.vue
> +      await this.loadPlushieData();
Добавил фикс для этого момента. Хотя не уверен что такой кейс возможен - т.к. sku  может измениться только при изменении маршрута, при этом query будет удалено

2022-12-30 05:19 UTC, soarer1004 commented on components/organisms/o-base-plushie-product-order-form.vue
> +        <p>{{ $t('All quantity discounts applied automatically at checkout:') }}</p>
Похоже, что динамический контент в Magento только для модалки со скидками - пофиксил. Остальные статические

2022-12-30 06:12 UTC, soarer1004 commented on pages/BasePlushieProduct.vue
> +      await this.loadPlushieData();
Передал еще раз этот момент так, чтобы не использовать напрямую `existingPlushieId`, а заполнять `plushieId` на основе `existingPlushieId` только если есть соответствующий продукт в корзине. В иных случаях просто создавать новый plushie. Т.к. `existingPlushieId`, теоретически может быть не корректным. В Forevers также примерно реализовано

2022-12-30 15:53 UTC, gorbunovav approved these changes

2022-12-30 15:53 UTC, merged