#27939: Allow to specify different eyes colors
BudsiesApp/vsf-capybara pull request #253
Opened 2023-03-20 03:53 UTC by soarer1004

2023-03-20 16:30 UTC, gorbunovav requested changes

2023-03-20 16:30 UTC, gorbunovav commented on components/molecules/m-bodypart-option-configurator.vue
> +      fShowDetailedBodyParts: false
unused field?

2023-03-20 16:30 UTC, gorbunovav commented on components/atoms/a-body-part-value.vue
> +    configuratorInstanceId: {
что еще за конфигуратор? (с точки зрения области знаний данного компонента)

2023-03-20 16:30 UTC, gorbunovav commented on components/organisms/OForeversCreationWizard/m-customize-step.vue
> +              :max-values="bodypart.maxValues"
есть ли смысл отдельно передавать maxValues, если ты уже целиком body part передаешь?

2023-03-21 09:07 UTC, soarer1004 commented on components/organisms/OForeversCreationWizard/m-customize-step.vue
> +              :max-values="bodypart.maxValues"
Целиком нет смысла передавать body part, это похоже осталось от предыдущей реализации(у конфигуратора такого параметра сейчас нет).

2023-03-21 16:03 UTC, gorbunovav approved these changes

2023-03-21 16:03 UTC, merged