#28682: Forevers Creation Wizard - tweak margins
BudsiesApp/vsf-capybara pull request #260
Opened 2023-04-07 04:39 UTC by soarer1004

2023-04-07 17:32 UTC, gorbunovav requested changes

2023-04-07 17:32 UTC, gorbunovav commented on components/organisms/OForeversCreationWizard/m-customize-step.vue
> +  }
А почему тут rem? Мы вроде стараемся переменные использовать для унификации (можно в крайнем случае calc использовать 🤔)

2023-04-10 04:39 UTC, soarer1004 commented on components/organisms/OForeversCreationWizard/m-customize-step.vue
> +  }
Да, тут лучше использовать `2 * --spacer-base`, исправил

2023-04-10 13:06 UTC, gorbunovav approved these changes

2023-04-10 13:06 UTC, merged