#28171: Add `Golf Head Covers` creation page
BudsiesApp/vsf-capybara pull request #261
Opened 2023-04-20 09:26 UTC by soarer1004

2023-04-20 16:18 UTC, gorbunovav requested changes

2023-04-20 16:18 UTC, gorbunovav commented on components/organisms/OPlushieCreationWizard/m-product-type-choose-step.vue
> +          imageSrc: '/assets/golf-covers/dog-icon.png'
а ты размеры картинок не оптимизировал?

2023-04-20 16:18 UTC, gorbunovav commented on components/organisms/OPlushieCreationWizard/m-customize-step.vue
> +      return this.plushieType === PlushieType.FOREVERS;
а можем такие вещи вынести в параметры и передавать из самого wizard'а?
(т.е. чтобы внутри субкомпонентов wizard'а не было логики, завязанной на тип - хочу сократить количество мест для изменения при доблавении новых типов продуктов)

2023-04-21 02:58 UTC, soarer1004 commented on components/organisms/OPlushieCreationWizard/m-product-type-choose-step.vue
> +          imageSrc: '/assets/golf-covers/dog-icon.png'
Да, не учел этот момент. Исправил

2023-04-21 09:35 UTC, gorbunovav approved these changes

2023-04-21 09:35 UTC, merged