24488 add product discount
BudsiesApp/vsf-capybara pull request #27
Opened 2021-08-09 03:38 UTC by soarer1004

2021-08-11 12:49 UTC, gorbunovav requested changes

2021-08-11 12:49 UTC, gorbunovav commented on components/organisms/o-product-card.vue
> +      <template #image="{image, title}">
я посмотрел - там в компоненте есть слот `badge` и получается есть функционал вывода бейджа - возможно проще его стилизовать, чем дублировать логику вывода изображения?

2021-08-11 12:49 UTC, gorbunovav commented on components/organisms/o-product-card.vue
> +      :score-rating="product.rating.score"
убери передачу занчений для рейтинга, пожалуйста - он нам не нужен пока (был скрыт до этого)

2021-08-11 12:49 UTC, gorbunovav commented on helpers/index.ts
> +    title: htmlDecode(product.name)
а верни title наверх - чтобы меньше конфликтов было при потенциальном обновлении.

2021-08-12 09:00 UTC, soarer1004 commented on components/organisms/o-product-card.vue
> +      <template #image="{image, title}">
Да, действительно. Переделал на `badge` слот

2021-08-12 09:04 UTC, soarer1004 commented on components/organisms/o-product-card.vue
> +      :score-rating="product.rating.score"
Убрал. Но до этого, рейтинг использовался в `o-search-panel`.  Но, похоже что этот компонент нигде не используется(Только в `o-header`, но там он закомментирован)

2021-08-12 09:06 UTC, soarer1004 commented on helpers/index.ts
> +    title: htmlDecode(product.name)
Исправил

2021-08-12 14:46 UTC, gorbunovav approved these changes

2021-08-12 14:46 UTC, merged