24677 checkout products
BudsiesApp/vsf-capybara pull request #28
Opened 2021-08-10 03:41 UTC by soarer1004

2021-08-11 14:07 UTC, gorbunovav requested changes

2021-08-11 14:07 UTC, gorbunovav commented on components/organisms/o-products-list-table.vue
> +<script>
нужно конвертировать в typescript.

2021-08-11 14:07 UTC, gorbunovav commented on components/organisms/o-products-list-table.vue
> +.table {
мне кажется корневой класс компонента должен быть более специфичным 🤔

2021-08-11 14:07 UTC, gorbunovav commented on components/organisms/o-products-list-table.vue
> +  @include for-desktop {
а перенести пожалуйста блок для размера экрана в конец - мы их обычно последними ставим, после других модификторов состояния.

2021-08-11 14:07 UTC, gorbunovav commented on components/organisms/o-products-list-table.vue
> +    productsInCart: {
давай `cartItems` назовем? я так понимаю это не просто объекты `Product`

2021-08-11 14:07 UTC, gorbunovav commented on components/organisms/o-products-list-table.vue
> +    tableHeaders: {
мне кажется список заголовков лучше внутри компонента определять - снаружи это сложно сделать, не зная выводимой разметки и логики ее формирования (т.е. это нарушение инкапсуляции компонента)

2021-08-11 14:07 UTC, gorbunovav commented on components/organisms/o-products-list-table.vue
> +    isHeaderShow: {
можно кстати `shouldShowHeader` - т.е. не обязательно всего имнно `is` использовать.

2021-08-12 11:33 UTC, soarer1004 commented on components/organisms/o-products-list-table.vue
> +<script>
Исправил

2021-08-12 11:33 UTC, soarer1004 commented on components/organisms/o-products-list-table.vue
> +.table {
Исправил

2021-08-12 11:33 UTC, soarer1004 commented on components/organisms/o-products-list-table.vue
> +  @include for-desktop {
Исправил

2021-08-12 11:37 UTC, soarer1004 commented on components/organisms/o-products-list-table.vue
> +    productsInCart: {
Согласен, компонент тоже переименовал в `o-cart-items-table`

2021-08-12 11:37 UTC, soarer1004 commented on components/organisms/o-products-list-table.vue
> +    tableHeaders: {
Исправил

2021-08-12 11:38 UTC, soarer1004 commented on components/organisms/o-products-list-table.vue
> +    isHeaderShow: {
Переименовал

2021-08-12 14:34 UTC, gorbunovav approved these changes

2021-08-12 14:34 UTC, merged