#29484: Category - mobile - fix products lazy loading
BudsiesApp/vsf-capybara pull request #290
Opened 2023-06-02 04:39 UTC by soarer1004

2023-06-03 13:08 UTC, gorbunovav requested changes

2023-06-03 13:08 UTC, gorbunovav commented on pages/Category.vue
> +          <div class="_observable" ref="observable" />
думаю лучше назвать как то вроде `_nextPageLoadingThreshold`

2023-06-03 13:08 UTC, gorbunovav commented on mixins/intersection-observer-mixin.ts
> +export default Vue.extend({
Сейчас вроде считается, что предпочтительнее composition API чем миксины использовать.

В 2.7 портировали нативную поддержку, для 2.6 плагин есть, который это реализует:
https://github.com/vuejs/composition-api

Можно попоробовать в качестве упраженения реализовать через этот подход.
https://stackoverflow.com/questions/67099111/vue-js-composition-api-mixins-and-life-cycle-hooks

Хотя тут возможно и просто без миксина можно обойтись - использовать просто класс, который всю логику в себе реализует и инициализировать его в mounted компонента, передавая нужные зависимости. Единственное  придется явно в beforeDestroy уничтожение вызывать..

2023-06-05 12:58 UTC, gorbunovav requested changes

2023-06-05 12:58 UTC, gorbunovav commented on helpers/use-items-lazy-loading.ts
> +): {
непонятное назначение компонента получилось - он по сути делает что?
решает активен ли lazy loading в зависимости от размера экрана?

при этом зачем ему loadItems? он же сам его никогда не триггерит
и зачем ему своя отдельная блокировка этого loadItems?

2023-06-05 12:58 UTC, gorbunovav commented on helpers/use-items-lazy-loading.ts
> +): {
вообще я так понял lazy loading - это типа как раз infinity scroll?
тогда видимо этот компонент должен реализовывать загрузку через intersection observer.

Ну и мне кажется компонент должен дергать метод загрузки, который ему передали, а уже тот пусть сам решает - заблокирован он сейчас или нет.
Если очень надо - можно снаружи передать флаг отключения.

2023-06-05 12:58 UTC, gorbunovav commented on helpers/use-items-lazy-loading.ts
> +): {
Еще я кстати не нашел как загрузка страниц реализована при отключенном lazy loading (через pagination)

2023-06-05 12:58 UTC, gorbunovav commented on pages/Category.vue
> +      browserWidth,
browserWidth вроде бы нигде не используется

2023-06-05 12:58 UTC, gorbunovav commented on pages/Category.vue
> +      );
а мы же создаем observer для одного элемента исключительно - зачем нам проверять, что это тот же элемент?

(ну и почему мы это делаем в обработчике, передаваемом компоненту, а не где то внутри компонента - это же по идее внтренняя деталь реализации `useIntersectionObservable` тогда)

2023-06-05 12:58 UTC, gorbunovav commented on pages/Category.vue
> +      );
еще - метод setup должен назначать обработчики, а не содержать их код целиком

2023-06-06 05:52 UTC, soarer1004 commented on helpers/use-items-lazy-loading.ts
> +): {
> непонятное назначение компонента получилось

Да, наверное, тут лучше назвать `useInfinityScroll` и использовать в нем `useIntersectionObservable`.

> Ну и мне кажется компонент должен дергать метод загрузки, который ему передали, а уже тот пусть сам решает - заблокирован он сейчас или нет.

Тут не уверен, `isLoadingItems` относится только к бесконечной подгрузке, как и `isInfinityScrollingEnabled`. Ну и получается логично, что проверка доступна ли загрузка и изменение состояния `isLoadingItems`, выполняется в этом composable.

> Еще я кстати не нашел как загрузка страниц реализована при отключенном lazy loading

В методе `changePage`, в нем просто вызывается `category-next/fetchPageProducts` экшен.

2023-06-06 11:44 UTC, gorbunovav commented on helpers/use-items-lazy-loading.ts
> +): {
неслабая там цепочка вызовов 🤪

2023-06-06 12:05 UTC, gorbunovav commented on helpers/use-items-lazy-loading.ts
> +): {
@soarer1004  Насчет `isLoadingItems` - получается, что это локальный флаг usable-компонента.
При этом в основном компоненте могут быть другие триггеры для загрузки продуктов.

Флаг из `useInfinityScroll` для отслеживания других вариантов загрузки использовать не логично - т.к. он из компонента для частного случая.

Тогда как минимум в компоненте Category для него название должно быть более спицифичным (что это именно для InfinityScroll флаг).

Плюс мы скорее всего не хотим, чтобы его меняли снаружи - т.к. его состоянием управляет `useInfinityScroll`.

С другой стороны во время загрузки продуктов в `Category` мы хотим блокировать все способы загрузки.
С этой точки зрения логичнее сделать общий флаг в самом `Category` , и блокировать на его основании `loadProducts`. 

Можно его передавать в `useInfinityScroll`, но с другой стороны там на его основании только загрузка блокируется - а она и в `Category`  будет блокироваться.

В теории можно сделать у `useInfinityScroll` какой то свой флаг, чтобы показывать, что загрузка была инициирована именно через него, но на практике нам сейчас вроде это не нужно.

2023-06-07 13:38 UTC, gorbunovav commented on pages/Category.vue
> +  isProductsLoading.value = false;
```suggestion
  try {
    isProductsLoading.value = true;
    await store.dispatch('category-next/loadMoreCategoryProducts');
  } finally {
    isProductsLoading.value = false;
  }
```

2023-06-07 15:42 UTC, gorbunovav approved these changes

2023-06-07 15:42 UTC, merged