#29087: MAddonsSelector - show images on mobile layout
BudsiesApp/vsf-capybara pull request #292
Opened 2023-06-02 09:25 UTC by soarer1004

2023-06-03 11:15 UTC, gorbunovav requested changes

2023-06-03 11:15 UTC, gorbunovav commented on components/molecules/m-addons-selector.vue
> +                <div class="_description-container">
по идее один div теперь лишний - в `_content` нет других элементов, кроме `_description-container`

2023-06-03 11:15 UTC, gorbunovav commented on components/molecules/m-addons-selector.vue
> +                  <div class="_image-column">
вроде нет колонок больше - соответственно названия `_info-column` / `_image-column` потеряли смысл.

2023-06-03 11:15 UTC, gorbunovav commented on components/molecules/m-addons-selector.vue
> +                  <div class="_description" v-html="addon.description" />
я думаю мы хотим чтобы у этого элемента (и у первого абзаца внутри) не было margin, а margin бы задвался у `_content`

2023-06-05 09:23 UTC, soarer1004 commented on components/molecules/m-addons-selector.vue
> +                <div class="_description-container">
@gorbunovav Там же еще блок для customOptions

2023-06-05 09:24 UTC, soarer1004 commented on components/molecules/m-addons-selector.vue
> +                <div class="_description-container">
@gorbunovav А, понял, это скорее всего про `_info-column`

2023-06-05 11:55 UTC, gorbunovav approved these changes

2023-06-05 11:55 UTC, merged