#29266: Bulk Requests / Bulk Sample creation pages - display errors list near the submit button
BudsiesApp/vsf-capybara pull request #294
Opened 2023-06-07 11:40 UTC by soarer1004

2023-06-13 14:57 UTC, gorbunovav requested changes

2023-06-13 14:57 UTC, gorbunovav commented on components/molecules/m-form-errors.vue
> +          @click="$emit('go-to-field', key)"
ты для названия события используешь контекст его использования - это некорректно

2023-06-13 14:57 UTC, gorbunovav commented on components/molecules/m-form-errors.vue
> +    filteredErrors (): Dictionary<string[]> {
а в связи с чем фильтровать приходится?

2023-06-13 14:57 UTC, gorbunovav commented on helpers/validate-form.function.ts
> +  goToFieldByName(fieldName, refs);
либо лучше назвать validateAndGoToFirstError, либо разделить валидацию и переход 🤔 (ну т.е. сначала вызывать валидацию, а потом, если она не прошла - вызывать переход к первой ошибке)

2023-06-13 14:57 UTC, gorbunovav commented on helpers/get-first-field-with-error-name.function.ts
> +export function getFirstFieldWithErrorName (
тут видимо лучше `getNameOfFirstFieldWithError` - иначе не  сразу понятно, что "Name" относится не к Error, а Field.

2023-06-13 14:57 UTC, gorbunovav commented on components/organisms/OBulkorders/o-bulk-quote-order-form.vue
> +      if (this.isDisabled || !isValid) {
по идее если она disabled, то и валидировать не нужно 🤔

2023-06-13 14:57 UTC, gorbunovav commented on helpers/get-field-anchor-name.function.ts
> +export function getFieldAnchorName (field: string): string {
предлагаю все эти функции попробовать объединить в re-usable компонет (composition API), потому что по отедльности они не очень универсальны - все завязано на существование refs'ов с именами сгенерированными через имена полей 🤔

2023-06-13 16:01 UTC, gorbunovav commented on helpers/get-field-anchor-name.function.ts
> +export function getFieldAnchorName (field: string): string {
я там подмержил petsies-ветку - теперь Composition API тут тоже доступно

2023-06-14 07:36 UTC, soarer1004 commented on components/molecules/m-form-errors.vue
> +    filteredErrors (): Dictionary<string[]> {
Поле `errors`, которое передается в scoped slot из `validationObserver` содержит все поля, но некоторые могут не содержать ошибок, поэтому их нужно отфильтровать

2023-06-19 20:16 UTC, gorbunovav requested changes

2023-06-19 20:16 UTC, gorbunovav commented on helpers/use-form-validation.ts
> +    validationObserver
а зачем `validationObserver` отсюда возвращать?
и где он задается? не нашел

2023-06-19 20:16 UTC, gorbunovav commented on components/organisms/OBulkorders/m-base-form.vue
> +        v-model="formData.name"
вообще ты получается тут меняешь напрямую свойства передаваемого объекта, что вроде как анти-паттерн (соответственно emit ниже никогда не выполняется).

2023-06-19 20:16 UTC, gorbunovav commented on components/organisms/OBulkorders/m-base-form.vue
> +      <input type="hidden" v-model="formData.customerImages">
тут видимо `:value` нужно - т.к. `input` не обновляет значение

2023-06-19 20:16 UTC, gorbunovav commented on components/organisms/OBulkorders/m-base-form.vue
> +        v-model="formData.name"
по идее можно оставить как до этого было, но использовать в родительской форме не `reactive`, а `ref` - тогда должно быть можно заменить объект в `.value`

2023-06-20 04:06 UTC, soarer1004 commented on helpers/use-form-validation.ts
> +    validationObserver
Он используется в шаблоне в качестве значения для ref атрибута `validation-observer`

2023-06-20 04:08 UTC, soarer1004 commented on helpers/use-form-validation.ts
> +    validationObserver
https://vuejs.org/guide/essentials/template-refs.html#accessing-the-refs

2023-06-20 09:06 UTC, gorbunovav commented on helpers/use-form-validation.ts
> +    validationObserver
@soarer1004 ого, они придумали.
А может тогда лучше ref создавать/возвращать локально в компоненте, а в `useFormValidation` передавать в качестве параметра? 
Тогда по крайней мере будет более понятно что происходит в `useFormValidation`, плюс за совпадение названия в ref'а в коде и в template все же отвечает конечный компонент.

2023-06-20 09:17 UTC, soarer1004 commented on helpers/use-form-validation.ts
> +    validationObserver
@gorbunovav Да, наверное, лучше так переделать. Дублирования не сильно больше, но гораздо понятней становится. Сейчас исправлю

2023-06-20 12:12 UTC, gorbunovav approved these changes

2023-06-20 12:12 UTC, merged