#30020: Add background for pages
BudsiesApp/vsf-capybara pull request #318
Opened 2023-07-31 08:09 UTC by soarer1004

2023-07-31 15:35 UTC, gorbunovav requested changes

2023-07-31 15:35 UTC, gorbunovav commented on components/molecules/m-bodypart-option-configurator.vue
> +    background-size: 280px 30px;
1. У меня не работает (путь не верный и вроде класс, к которому прменяется тоже).
2. Мы можем это вынести в подкласс для темы? чтобы легче мержить и отслеживать изменения было

2023-07-31 15:35 UTC, gorbunovav commented on pages/ClayProduct.vue
> +    <div class="_clouds-container" />
Можем мы это попробовать применить ко всем страница и вынести на уровень layout'а, чтобы не прописывать на каждой странице?

Единственное - с текущей версией страницы gift cards это не работает - облака накладываются на форму карты.

И облака сейчас в целом на текст накладываюстя (например страница создания Selfie) - мне кажется выглядит странно

2023-08-01 06:06 UTC, soarer1004 commented on pages/ClayProduct.vue
> +    <div class="_clouds-container" />
Можем сделать для всех страниц, но я специально добавил только для определенных страниц - в Magento сделано таким же образом. И плюс на странице Gift Cards правое облако должно заменяться на другое изображение и если сделать глобально - переопределять его будет менее удобно. Перекрывание контента обаками пофиксил.

2023-08-02 03:43 UTC, soarer1004 commented on pages/ClayProduct.vue
> +    <div class="_clouds-container" />
@gorbunovav Тут проблема получается. Если добавлять для всех страниц - нужно делать на уровне компонента `layout/Default`. В таком случае стили будут применены и для Storyblok страниц. Чтобы определить Storyblok страницу и не добавлять соответствующие стили можно через проверку имени `route` - динамически добавленые страницы имеют в имени префикс `urldispatcher-`. Но также этот префикс будут иметь страницы, которые через url-rewrite роутятся. Поэтому этот способ определения Storyblok страниц не очень подходит.

По идее `mappingFallback` возвращает route у которого `name` более конкретный - `storyblok-page` и `url-rewrite`. Как вариант можно это название добавлять как префикс к `urldispatcher-`. Тогда можно будет в `layout/Default` точно определить что отображаемая страница - это Storyblok страница и не применять стили.

2023-08-18 10:32 UTC, gorbunovav approved these changes

2023-08-18 10:32 UTC, merged