24397 plushie edit
BudsiesApp/vsf-capybara pull request #32
Opened 2021-09-02 07:22 UTC by soarer1004

2021-10-09 17:15 UTC, gorbunovav requested changes

2021-10-09 17:15 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +      default: ''
а почему пустая строка? если значения нет - то логичнее `undefined`

2021-10-09 17:15 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +    }),
Есть предложение не использовать map-функции, т.к. типизации нет.
Вместо этого прописыать руками getter и указывать у него тип возвращаемого значения 🤔

(или найти какой то способ сохранять типизацию)

2021-10-09 17:15 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +        return null;
а почему null, а не undefined?

и кстати просто find нельзя использовать? 🤔

2021-10-09 17:15 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +    }),
наверное аналогично getter'ам выше

2021-10-09 17:15 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +            customerImages: this.imageUploadStepData.storageItems
получается вроде как дублирование информации?

может быть достаточно `storageItems` передавать, а там, где нужны ID их уже из них получать?

И вроде бы еще логика отличается - в `getStorageItemsIds` есть провеврка метода выбранного загрузки, а для `customerImages` - получается нет.  

И кстати как сервер это поле обрабатывает? По идее он должен возвращать знечения для него, иначе если cart item будет подгружен с сервера, то там поля не будет

2021-10-09 17:15 UTC, gorbunovav commented on components/molecules/m-artwork-upload.vue
> +        source: `${config.images.imageHandlerServiceUrl}/${item.url}`,
Лучше наверное какой то сервис сделать, который будет за формирование url'ок к картиркам отвечать 🤔
Типа такого:
https://github.com/GorbunovStudio/budsies-backend-ui-app/blob/94a82e408d222ef6f00d775d613225fdaec4b671/src/modules/file-storage/image-handler.service.ts

2021-10-09 17:15 UTC, gorbunovav commented on components/organisms/OForeversCreationWizard/m-image-upload-step.vue
> +      console.log('onRemove', storageItemId);
забыл убрать

2021-10-09 17:15 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +          this.customizeStepData.bodypartsValues,
лучше на всякий случай очистить текущие значения предварительно

2021-10-09 17:15 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +      this.productTypeStepData.product = { ...cartItem };
а нам тут именно копия нужна?

2021-10-19 04:47 UTC, soarer1004 commented on components/organisms/o-forevers-creation-wizard.vue
> +      this.productTypeStepData.product = { ...cartItem };
Как я понимаю, этот параметр может изменяться. И исходный объект мы бы не хотели мутировать

2021-10-20 02:59 UTC, soarer1004 commented on components/organisms/o-forevers-creation-wizard.vue
> +      this.productTypeStepData.product = { ...cartItem };
Хотя, свойства этого объекта нигде не меняются. И присваиваются новые значения для `productTypeStepData`. Так что можно исходный объект без копии использвать. Исправил

2021-10-20 14:57 UTC, gorbunovav approved these changes

2021-10-20 15:00 UTC, merged