#29868: Raffle - implement page
BudsiesApp/vsf-capybara pull request #325
Opened 2023-08-09 09:12 UTC by soarer1004

2023-08-14 15:41 UTC, gorbunovav requested changes

2023-08-14 15:41 UTC, gorbunovav commented on pages/Raffle.vue
> +    },
вроде нигде не используется в итоге

2023-08-14 15:41 UTC, gorbunovav commented on pages/Raffle.vue
> +    }
что то недоделано?

2023-08-15 03:39 UTC, soarer1004 commented on pages/Raffle.vue
> +    }
@gorbunovav Пропустил этот момент. Мы же, получается, хотели использовать storyblok блоки для верхней части страницы. Но этих блоков пока что нет. Наверное их стоит отдельной задачей добавить?

2023-08-15 21:25 UTC, gorbunovav approved these changes

2023-08-15 21:25 UTC, merged