#30351: Budsies theme - Feedback 2023-08-25
BudsiesApp/vsf-capybara pull request #341
Opened 2023-08-29 09:02 UTC by soarer1004

2023-08-29 11:14 UTC, gorbunovav requested changes

2023-08-29 11:14 UTC, gorbunovav commented on pages/CrossSells.vue
> +              (!!product.landing_page_url || isUpSells)
@soarer1004 по идее тут дело не в том, что они "upsells", а в том, что это аксессуары, у которыз есть страница продукта. Видимо можно не требовать наличия landing page для не-custom продуктов.

2023-08-29 11:14 UTC, gorbunovav commented on css/base/_variables.scss
> +$color-error: #fa5347;
вроде эта переменная нигде не используется.

2023-08-29 11:14 UTC, gorbunovav commented on css/base/_variables.scss
>      @include generate-color-variants(--_c-light-primary, #f78f9e);
а почему у нас для `--_c-light-primary` красный используется? вроде же у нас нет красного особо в теме (кроме ошибок / варианта акцента)

2023-08-29 12:45 UTC, gorbunovav requested changes

2023-08-29 12:45 UTC, gorbunovav commented on css/base/_variables.scss
> +    --c-accent: var(--_c-green-primary);
выше есть еще какая то переменная `$color-accent`

2023-08-30 07:04 UTC, soarer1004 commented on css/base/_variables.scss
> +    --c-accent: var(--_c-green-primary);
Похоже что эти scss переменные цветов нигде не используются, думаю их можно удалить.

2023-08-30 07:13 UTC, soarer1004 commented on css/base/_variables.scss
>      @include generate-color-variants(--_c-light-primary, #f78f9e);
Похоже этот цвет остался с темы Petsies

2023-08-30 07:14 UTC, soarer1004 commented on css/base/_variables.scss
>      @include generate-color-variants(--_c-light-primary, #f78f9e);
Он используется еще в качестве значения переменной `--c-warning`

2023-08-30 12:58 UTC, gorbunovav approved these changes

2023-08-30 12:58 UTC, merged