#24536: Display prices with campaign discounts
BudsiesApp/vsf-capybara pull request #36
Opened 2021-10-20 10:51 UTC by soarer1004

2021-10-21 22:23 UTC, gorbunovav requested changes

2021-10-21 22:23 UTC, gorbunovav commented on helpers/price.ts
> +  const productCampaignDiscount = store.getters['promotionPlatform/getProductCampaignDiscount'](product, format);
Можем использовать EventBus (у них тут используется) или какой то вариант глобальных action'ов / getter'ов из Vuex чтобы здесь условно выбрасывать какое то общее событие/вызывать геттер типа getProductDiscount, а  в нашем модуле promotional campaign уже его реализовать и возвращать значение?

2021-10-25 03:45 UTC, soarer1004 commented on helpers/price.ts
> +  const productCampaignDiscount = store.getters['promotionPlatform/getProductCampaignDiscount'](product, format);
Как я понимаю, в случае с EventBus или action этот метод станет асинхронным. Тогда этот вариант нам не подходит т.к. `getProductDiscount` в основном используется в `computed` свойствах. Глобальный геттер в проекте вообще только один - `getCurrentStoreView`. В остальных случаях всё в модулях реализовано. Я правильно понимаю, что смысл этих изменений в том чтобы не привязывать этот helper к модулю `promotionPlatform`?

2021-10-25 06:56 UTC, gorbunovav commented on helpers/price.ts
> +  const productCampaignDiscount = store.getters['promotionPlatform/getProductCampaignDiscount'](product, format);
> Я правильно понимаю, что смысл этих изменений в том чтобы не привязывать этот helper к модулю promotionPlatform?

@soarer1004 да.
А в случае с EventBus там за счёт чего асинхронность появляется?

2021-10-25 08:13 UTC, gorbunovav commented on helpers/price.ts
> +  const productCampaignDiscount = store.getters['promotionPlatform/getProductCampaignDiscount'](product, format);
@soarer1004 а, ну emit вообще не ждёт завершения обработки события

2021-10-25 08:17 UTC, gorbunovav commented on helpers/price.ts
> +  const productCampaignDiscount = store.getters['promotionPlatform/getProductCampaignDiscount'](product, format);
@soarer1004 хотя промисов там внутри тоже нет - так что по идее синхронное выполнение

2021-10-25 10:22 UTC, gorbunovav requested changes

2021-10-25 10:22 UTC, gorbunovav commented on helpers/price.ts
> +  const productCampaignDiscount = productCampaignDiscountData.value;
Ты в названии переменных все равно сохраняешь отсылку к promotional campaign.
Т.к. мы делаем тут просто точку расширения логики на основе события и не хотим завязываться на какие то конкретные модули - то лучше назвать как то более обобщенно (я предлагал в первом комментарии)

Второй момент - а зачем нам выполнять форматирование в обработчиках события? это не очень логично - проще же оттуда просто цифровые значения получать, а в этой функции уже форматировать итоговые результаты так, как это нужно для вывода итоговой цены.

2021-10-26 13:12 UTC, gorbunovav commented on interfaces/update-product-discount-price-data-event.interface.ts
> +  value?: number | string
@soarer1004 а у нас остался кейс, когда значение string? 🤔

2021-11-02 12:26 UTC, merged

2021-11-02 12:26 UTC, gorbunovav approved these changes