#30568: Product Order Forms - improve customer data persisting
BudsiesApp/vsf-capybara pull request #374
Opened 2023-10-18 03:59 UTC by soarer1004

2023-10-18 15:08 UTC, gorbunovav requested changes

2023-10-18 15:08 UTC, gorbunovav commented on components/organisms/OPlushieCreationWizard/m-pet-info-step.vue
> +      ...usePersistedEmail(email)
вообще, учитывая, что значения email приходит снаружи и сохраняется тоже снаружи - более логичной выглядит обработку пред-заполнения делать там же (сюда можно флаг передавать - показывать поле с мылом или нет).

2023-10-18 15:08 UTC, gorbunovav commented on components/organisms/o-billing-address.vue
> +import { LAST_USED_CUSTOMER_FIRST_NAME, LAST_USED_CUSTOMER_LAST_NAME, LAST_USED_CUSTOMER_PHONE_NUMBER, SET_LAST_USED_CUSTOMER_FIRST_NAME, SET_LAST_USED_CUSTOMER_LAST_NAME, SET_LAST_USED_CUSTOMER_PHON
а почему не везде получилось использовать композицию?

2023-10-18 15:08 UTC, gorbunovav commented on pages/GiftCards.vue
> +import { LAST_USED_CUSTOMER_FIRST_NAME, LAST_USED_CUSTOMER_LAST_NAME, SET_LAST_USED_CUSTOMER_EMAIL, SN_PERSISTED_CUSTOMER_DATA } from 'src/modules/persisted-customer-data';
часть импортов не используется

2023-10-25 05:02 UTC, soarer1004 commented on components/organisms/o-billing-address.vue
> +import { LAST_USED_CUSTOMER_FIRST_NAME, LAST_USED_CUSTOMER_LAST_NAME, LAST_USED_CUSTOMER_PHONE_NUMBER, SET_LAST_USED_CUSTOMER_FIRST_NAME, SET_LAST_USED_CUSTOMER_LAST_NAME, SET_LAST_USED_CUSTOMER_PHON
@gorbunovav Насколько я помню была проблема с использованием миксинов вместе с composition api. Правда она вроде была с TS связана, но  в целом не стал перемешивать миксины с composable, а если заменять используемые в компонентах миксины, то много изменений получается и по идее они к этой задаче не относятся особо.

2023-10-25 20:01 UTC, gorbunovav commented on components/organisms/o-billing-address.vue
> +import { LAST_USED_CUSTOMER_FIRST_NAME, LAST_USED_CUSTOMER_LAST_NAME, LAST_USED_CUSTOMER_PHONE_NUMBER, SET_LAST_USED_CUSTOMER_FIRST_NAME, SET_LAST_USED_CUSTOMER_LAST_NAME, SET_LAST_USED_CUSTOMER_PHON
https://redmine.optimuspro.ru/issues/29266#note-15

2023-10-30 10:45 UTC, gorbunovav commented on components/organisms/o-add-address-form.vue
> +    });
@soarer1004 а мы получается тут не можем сделать поля с именем и телефоном частью объекта addressData?

2023-10-30 10:53 UTC, soarer1004 commented on components/organisms/o-add-address-form.vue
> +    });
@gorbunovav По идее можем, но если я правильно понимаю, нужно будет все равно отдельные computed добавлять для этих полей, чтобы можно было их в composable передавать

2023-10-30 10:58 UTC, gorbunovav commented on components/organisms/o-add-address-form.vue
> +    });
а, у нас же там при set объект целиком заменяется - тогда computable затруться, даже если в полях будут у старого

2023-10-30 15:18 UTC, gorbunovav commented on pages/GiftCards.vue
> +import { LAST_USED_CUSTOMER_FIRST_NAME, LAST_USED_CUSTOMER_LAST_NAME, SN_PERSISTED_CUSTOMER_DATA } from 'src/modules/persisted-customer-data';
А тут мы не хотим сохранять email? 
Просто мне не нравится, что мы внутренности composable наружу вытаскиваем.

С компонентами, где mixin'ы используется - мы пока другого способа не нашли - там понятно.

2023-10-31 06:38 UTC, soarer1004 commented on pages/GiftCards.vue
> +import { LAST_USED_CUSTOMER_FIRST_NAME, LAST_USED_CUSTOMER_LAST_NAME, SN_PERSISTED_CUSTOMER_DATA } from 'src/modules/persisted-customer-data';
@gorbunovav Тут email, по идее не пользователя, а получателя подарочной карты. Думаю не имеет смысл его сохранять? А с именем пользователя тут не понятно, т.к. поле одно и в каком порядке пользователь его введет не известно(фамилия имя/имя фамилия или просто имя). Поэтому не уверен что эти данные мы можем тут сохранять тоже

2023-10-31 09:47 UTC, gorbunovav commented on pages/GiftCards.vue
> +import { LAST_USED_CUSTOMER_FIRST_NAME, LAST_USED_CUSTOMER_LAST_NAME, SN_PERSISTED_CUSTOMER_DATA } from 'src/modules/persisted-customer-data';
@soarer1004 так а зачем его тогда заполнять, если это не пользователя? 🤔

2023-10-31 09:50 UTC, soarer1004 commented on pages/GiftCards.vue
> +import { LAST_USED_CUSTOMER_FIRST_NAME, LAST_USED_CUSTOMER_LAST_NAME, SN_PERSISTED_CUSTOMER_DATA } from 'src/modules/persisted-customer-data';
@gorbunovav Тут только имя отправителя подарочной карты заполняется, email нет

2023-11-01 12:49 UTC, gorbunovav approved these changes

2023-11-01 12:49 UTC, merged