#30914: Product view page - display cross-sells products similar to upgrades list
BudsiesApp/vsf-capybara pull request #381
Opened 2023-10-27 14:12 UTC by soarer1004

2023-10-30 11:03 UTC, gorbunovav commented on components/atoms/a-add-to-cart.vue
> +      default: () => ([])
а есть смысл делать отдельное свойство? или может лучше все в одном передавать? (ты все равно дальше все продукты объединяешь)

2023-10-30 13:29 UTC, gorbunovav requested changes

2023-10-30 13:29 UTC, gorbunovav commented on helpers/use-cross-sells-products.ts
> +      for (const key in productBySkuDictionary.value) {
а если это dictionary - то наверное можно просто по ключу обратиться и нет смысла перебирать все значения?

2023-10-30 13:29 UTC, gorbunovav commented on helpers/use-cross-sells-products.ts
> +      for (const key in productBySkuDictionary.value) {
см выше

2023-10-30 13:29 UTC, gorbunovav commented on helpers/use-cross-sells-products.ts
> +          products.push(productBySkuDictionary.value[key]);
у нас вроде продукт уже в переменной `product`

2023-10-30 13:29 UTC, gorbunovav commented on helpers/use-form-validation.ts
> +export function getFieldAnchorName (field: string): string {
а нам надо эту функцию экспортировать? вроде не используется

2023-10-30 13:29 UTC, gorbunovav commented on helpers/use-cross-sells-products.ts
> +  listTypes: (ListType)[] = [CROSS_SELL, UP_SELL],
какой то оптимизации загрузки связей вроде нет - поэтому возможно лучше не пытаться загружать несколько типов а реализовать загрузку одного, а там, где нужно нескольких связей - использовать его несколько раз. 
(можно еще загрузку related продуктов добавить)
(и название тогда для composable related products использовать - т.к. это все подвиды связанных продуктов)

2023-10-30 13:29 UTC, gorbunovav commented on helpers/use-cross-sells-products.ts
> +    crossSellsProductDictionary,
А мы можем не хэш наружу показывать, а вместо этого дать доступ к функции, которая будет возвращать продукт по sku? (а она уже тут внутри будет работать с хэшем).

2023-10-30 15:24 UTC, gorbunovav commented on components/organisms/o-cross-sells-products-selector.vue
> +      ['crosssell'],
возможно лучше константу использовать?

2023-10-31 03:48 UTC, soarer1004 commented on helpers/use-cross-sells-products.ts
> +      for (const key in productBySkuDictionary.value) {
@gorbunovav Тут если я правильно понимаю так сделано потому что сравнение происходит с `parentSku`. Возможно лучше в отдельной задаче проверить в каких случаях `sku` может быть изменен и либо везде тогда `parentSku` использовать в качестве идентификатора либо убрать возможность подмены `sku`.

2023-10-31 04:59 UTC, soarer1004 commented on helpers/use-form-validation.ts
> +export function getFieldAnchorName (field: string): string {
Используется в `o-cross-sells-products-selector` - передается в `m-addons-selector` т.к. этот параметр обязательный.

2023-10-31 05:07 UTC, soarer1004 commented on helpers/use-cross-sells-products.ts
> +  listTypes: (ListType)[] = [CROSS_SELL, UP_SELL],
@gorbunovav Продукты паралельно загружаются если несколько типов используется. Плюс может быть проблема с загрузкой основного продукта.  Если использовать отдельные инстансы composable для разных списков нужно тогда отдельную функцию для загрузки основного продукта добавлять, затем в компоненте загружать основной продукт и затем паралельно загружать списки продуктов если несколько типов используется на странице.

2023-10-31 05:18 UTC, soarer1004 commented on helpers/use-cross-sells-products.ts
> +  listTypes: (ListType)[] = [CROSS_SELL, UP_SELL],
@gorbunovav Ну или можно вместо `parentSku` передавать сразу продукт, а загрузку продукта вынести в отдельный composable

2023-10-31 06:16 UTC, soarer1004 commented on components/atoms/a-add-to-cart.vue
> +      default: () => ([])
@gorbunovav Там в родительском компоненте есть watcher который обновляет количество после изменения продукта, он основан на основном продукте. Поэтому решил не менять этот момент пока что и передавать отдельным параметром.

2023-10-31 06:17 UTC, soarer1004 commented on helpers/use-cross-sells-products.ts
> +  listTypes: (ListType)[] = [CROSS_SELL, UP_SELL],
@gorbunovav Вынес логику загрузки основного продукта в отдельный composable

2023-10-31 14:11 UTC, gorbunovav commented on helpers/use-product.ts
> +    }
@soarer1004 тут не понимаю - вызывается же getter - он ничего не устанавливает.
Если это отражение режимов работы использующего consumable компонента - то это не очевидно.

Вообще ты этот consumable только в одном месте используешь - соответственно особой пользы от него не вижу.

В теории можно сделать подобный consumable, но надо анализировать тогда несколько компонентов и решать какие части имеет смысл выносить для унификации.

2023-10-31 14:13 UTC, gorbunovav commented on helpers/use-cross-sells-products.ts
> +      for (const key in productBySkuDictionary.value) {
а в качестве ключа в хэше используется sku, который может быть заменен? (тогда получается хэш не очень полезный)

2023-10-31 14:15 UTC, gorbunovav commented on helpers/use-cross-sells-products.ts
> +  listTypes: (ListType)[] = [CROSS_SELL, UP_SELL],
@soarer1004  Под оптимизацией загрузки я имел ввиду, например, загрузку всех списков одним запросом. 
А так получается нет разницы - все равно запросы из всех инстансов consumable будут параллельно выполняться.

2023-11-01 03:55 UTC, soarer1004 commented on helpers/use-product.ts
> +    }
@gorbunovav Согласен, не очевидно получилось. В целом пока что смысла от этого composable не много получилось. Удалил этот composable и вернул загрузку продукта в компонент.

2023-11-01 06:58 UTC, gorbunovav approved these changes

2023-11-01 06:58 UTC, merged