#30942: Routes - get rid of `slug` param for products and tweak categories slug
BudsiesApp/vsf-capybara pull request #388
Opened 2023-11-08 07:16 UTC by soarer1004

2023-11-14 12:26 UTC, gorbunovav requested changes

2023-11-14 12:26 UTC, gorbunovav commented on pages/Category.vue
> +      return `https://${host}/c/${url_key}/`;
а мы можем использовать Router и маршрут с именем `category` для генерации url? 🤔

2023-11-14 12:26 UTC, gorbunovav commented on pages/Product.vue
> +      return `https://${host}/p/${this.$route.params.parentSku}/`;
и тут тоже - можно Router использовать? (и там по идее еще child SKU есть для configurable продуктов)

2023-11-14 12:26 UTC, gorbunovav commented on pages/Category.vue
> +        await this.onCategoryChangedHandler(from);
а почему нам приходится проверять и в `beforeRouteEnter` и в `beforeRouteUpdate`?
И почему мы тут второй раз вызываем `onCategoryChangedHandler`, но для `from`?

И можем ли мы основной код для работы с url rewrite оставить в соответствующем модуле? (загрузку rewrit'ов c сервера, например)

2023-11-15 07:28 UTC, soarer1004 commented on pages/Category.vue
> +        await this.onCategoryChangedHandler(from);
@gorbunovav `beforeRouteEnter` не отрабатывает когда меняются параметры маршрута, поэтому в `beforeRouteUpdate` также нужно проверять.

`onCategoryChangedHandler` второй раз вызывается для случая когда происходит переход со страницы категории на эту же страницу, но по ссылке которая приводит к редиректу через `url-rewrite`. Порядок в этом случае такой:
1. Меняется параметр маршрута;
2. Происходит попытка загрузить категорию;
3. Категория не найдена - получаем редирект;
4. Редирект ведет на текущую страницу;

Больше никакие хуки не отрабатывают и страница не изменяется. Поэтому нужно вызвать `onCategoryChangedHandler` второй раз. В ином случае продукты для категории остануться от категории, которая была не найдена и с которой произошел редирект(т.е. список будет пуст).

> И можем ли мы основной код для работы с url rewrite оставить в соответствующем модуле

Имеешь ввиду вообще редиректы не загружать в компоненте?

2023-11-15 07:57 UTC, gorbunovav commented on pages/Category.vue
> +        await this.onCategoryChangedHandler(from);
>Редирект ведет на текущую страницу;

@soarer1004 но на другую категорию, так? а почему тогда `this.onCategoryChangedHandler` вызывается для `from`, а не для `rewriteRouteData.params`?

>Имеешь ввиду вообще редиректы не загружать в компоненте?

например, сделать как `mapFallbackUrl` - просто вызывается функция из модуля, а она внутри уже ищет rewrite и т.п.

2023-11-15 08:10 UTC, soarer1004 commented on pages/Category.vue
> +        await this.onCategoryChangedHandler(from);
@gorbunovav 

> но на другую категорию, так

Нет, это кейс именно с такой же категорией. Т.е. тут в итоге получается переход `c/category` -> `c/category`. `rewriteRouteData.params` - это не параметры категории, а параметры для `url-rewrite` маршрута, который содержит только путь.

> просто вызывается функция из модуля, а она внутри уже ищет rewrite и т.п.

Не уверен, что удобно получится - т.к. в компоненте категории дополнительные действия требуются, например в `beforeRouteUpdate`. Т.е. тут получается все равно в компонент придется возвращать данные о редиректе. И получается будет функция такая же как текущий `urlRewrite/loadUrlRewrite` action

2023-11-15 09:24 UTC, gorbunovav commented on pages/Category.vue
> +        await this.onCategoryChangedHandler(from);
@soarer1004 хм, но по идее в `checkForRewriteRoute` ты используешь две функции из `modules/url-rewrite` подряд - экшен загрузки рерайта с сервера и `getUrlRewriteRouteData` . По идее это можно заменить на одну функцию, т.к. то, что нужно сходить на сервер за рерайтом - это детали реализации модуля.

И в `serverPrefetch` там вроде нет доп действий после загрузки рерайта.

2023-12-07 16:13 UTC, gorbunovav approved these changes

2023-12-07 16:13 UTC, merged