24398: Vue Storefront - add cross-sells page
BudsiesApp/vsf-capybara pull request #39
Opened 2021-10-25 07:26 UTC by fand0rin

2021-11-02 20:41 UTC, gorbunovav requested changes

2021-11-02 20:41 UTC, gorbunovav commented on pages/CrossSells.vue
> +    <div class="_cross-sells-list">
может быть не отображать список когда нет элементов?

2021-11-02 20:41 UTC, gorbunovav commented on pages/CrossSells.vue
> +            :link="crossSellsProduct.landing_page_url ? crossSellsProduct.landing_page_url : ''"
лушче наверное `undefined` передавать, когда нет значения 🤔 (пустая строка - это все же какое то значение)

2021-11-02 20:41 UTC, gorbunovav commented on pages/CrossSells.vue
> +            :link="upSellsProduct.landing_page_url ? upSellsProduct.landing_page_url : ''"
см выше

2021-11-02 20:41 UTC, gorbunovav commented on pages/CrossSells.vue
> +    })
сделай лучше computed свойство вручную - там тогда можно тип возвращаемого значения задать

2021-11-02 20:41 UTC, gorbunovav commented on pages/CrossSells.vue
> +    await this.loadUpSellsProducts();
В `asyncData` насколько я понимаю данные загружаются до отоюражения страницы (в т.ч. при server-side рендеринге).
Наверное имеет смысл все там загрузить?

2021-11-02 20:41 UTC, gorbunovav commented on pages/CrossSells.vue
> +      if (!productLinks || productLinks.length === 0) {
вроде productLinks всегда массив - т.е. первого кейса нет

2021-11-02 20:41 UTC, gorbunovav commented on pages/CrossSells.vue
> +      let skus = productLinks ? productLinks
у тебя выше проверка на то, что `productLinks` определена

2021-11-02 20:41 UTC, gorbunovav commented on pages/CrossSells.vue
> +  @include for-desktop {
желательно медиа-запросы помещать в конец, как мы в других проектах делаем

2021-11-02 20:43 UTC, gorbunovav commented on router/index.js
> +  { name: 'cross-sells', path: '/cross-sells/p/:parentSku/:slug', component: CrossSells },
а для чего второй параметр - `slug`?

2021-11-09 09:41 UTC, fand0rin commented on pages/CrossSells.vue
> +    await this.loadUpSellsProducts();
В `asyncData` получается методы недоступны

2021-11-10 18:02 UTC, gorbunovav approved these changes

2021-11-10 18:02 UTC, merged