#30708: Checkout Forms - add scroll to first field with error
BudsiesApp/vsf-capybara pull request #396
Opened 2023-11-30 09:32 UTC by soarer1004

2023-12-04 09:57 UTC, gorbunovav requested changes

2023-12-04 09:57 UTC, gorbunovav commented on components/molecules/m-password.vue
> +      }
так а если на форме есть еще поля с неверными значениями и они идут раньше? 🤔

2023-12-04 09:57 UTC, gorbunovav commented on helpers/vuelidate-scroll-to-first-error.function.ts
> +export function vuelidateScrollToFirstError (): void {
мне кажется лучше передавать элемент/класс контейнера, чтобы ограничить поиск и случайно не проскроллить к ошибке в какой то другой форме

2023-12-05 05:23 UTC, soarer1004 commented on components/molecules/m-password.vue
> +      }
Это сработает, т.к. скролл к элементам формы вызывается позже. Но переделал на более явный способ

2023-12-05 11:37 UTC, gorbunovav commented on helpers/vuelidate-scroll-to-first-error.function.ts
> +export function vuelidateScrollToFirstError (): void {
@soarer1004  так а может проще передавать что то вроде this.$el, чем пытаться сделать уникальный класс?
тогда гарантированно будет поиск в текущем компоненте

2023-12-06 11:50 UTC, gorbunovav approved these changes

2023-12-06 11:50 UTC, merged