25419 pillow customizer
BudsiesApp/vsf-capybara pull request #44
Opened 2021-11-12 03:20 UTC by soarer1004

2021-11-15 14:50 UTC, gorbunovav requested changes

2021-11-15 14:50 UTC, gorbunovav commented on components/organisms/o-phrase-pillow-product-order-form.vue
> +      flex-direction: row;
в Magento сейчас немного другие breakpoint'ы используются для переключения состояния - по идее имеет смысл перенести сюда те значения, т.к. иначе, например, на телефонах меньше iPhone X (в реальности и на нем) в landscape режиме нельзя пользоваться.

2021-11-15 14:50 UTC, gorbunovav commented on components/molecules/m-background-editor.vue
> +          class="_zoom-button _zoom-in"
Надо наверное найти какие то более подходящие иконки (типо лупы в Magento) - без шкалы стало совсем непонятно что это за стрелочки.

2021-11-15 14:50 UTC, gorbunovav commented on pages/GiftCards.vue
> +    --modal-content-font-size: var(--font-size-base);
а это в связи с чем правки?

2021-11-16 05:47 UTC, soarer1004 commented on pages/GiftCards.vue
> +    --modal-content-font-size: var(--font-size-base);
@gorbunovav Это я пофиксил момент с неправильным размеров шрифтов, когда превью подарочного сертификата открывается в модальном окне, забыл упомянуть в таске об этом. Наверное лучше будет лучше размер шрифтов для превью задать в самом компоненте превью. Исправлю сейчас

2021-11-16 12:32 UTC, gorbunovav approved these changes

2021-11-16 12:33 UTC, merged