#32425: Colors List Widget - add border for items
BudsiesApp/vsf-capybara pull request #462
Opened 2024-07-02 05:56 UTC by soarer1004

2024-07-03 17:48 UTC, gorbunovav requested changes

2024-07-03 17:48 UTC, gorbunovav commented on components/customization-system/widgets/thumbnails-list-widget.vue
> +    --base-list-widget-item-relative-width: 33.33%;
@soarer1004 
1. Раньше в размер iPhone 12 влезало 3 иконки, сейчас 2. Можешь сделать чтобы 3 помещалось?
2. В чем смысл этих процентов? Они же не соответствуют реальности. Т.е. тут вроде как 3 элемента на экран должно влезать, но по факту в верстке это не так и не похоже чтобы этот параметр на что то влял. Если нужны разные режимы отображения в зависимости от формы создания - можно сделать входные properties, через которые переключать режим виджета

2024-07-04 04:22 UTC, soarer1004 commented on components/customization-system/widgets/thumbnails-list-widget.vue
> +    --base-list-widget-item-relative-width: 33.33%;
@gorbunovav Названия переменных кривые были - это по идее ширина(в процентах) и максимальная ширина. Переименовал и откатил изменения для этого виджета(Сейчас отображается также как в формах без кастомизаций)

2024-07-04 10:45 UTC, gorbunovav approved these changes

2024-07-04 10:45 UTC, merged