#24760: Send GoogleAnalytics events and update dataLayer
BudsiesApp/vsf-capybara pull request #54
Opened 2021-11-26 08:50 UTC by soarer1004

2021-11-26 13:56 UTC, gorbunovav requested changes

2021-11-26 13:56 UTC, gorbunovav commented on pages/DetailedCart.vue
> +      })
Это похоже какой то рудимент - было отслеживание события добавления в корзину через факт загрузки страницы корзины.
Я посмотерл в экспортированных настройках контейнера GTM - эти переменные для пикселей, связанных с этой страницей не используются (похоже были переписаны).

Т.е. я думаю можно убрать.

2021-11-26 13:56 UTC, gorbunovav commented on pages/Product.vue
> +      );
Я посмотрел - судя по всему мы можем использовать `trackEvent` - данные точно также добавляются в dataLayer и потом доступны для триггеров/пикселей.

2021-11-26 13:56 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +      })
это тоже рудимент

2021-11-26 13:56 UTC, gorbunovav commented on components/organisms/o-order-confirmation.vue
> +      return product.category.map((category) => category.name).join('|');
у меня тут упало:
```
vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'map')
```

2021-11-26 13:56 UTC, gorbunovav commented on components/organisms/o-order-confirmation.vue
> +      this.window.dataLayer.push(
тоже можем `trackEvent` использовать

2021-11-26 13:56 UTC, gorbunovav commented on components/organisms/o-order-confirmation.vue
> +          actionName: 'Purchase Success',
Здесь `actionName` тоже можно убрать.

2021-11-26 13:56 UTC, gorbunovav commented on components/organisms/o-order-confirmation.vue
> +          shareasaleSSCID: '', // TODO
недоделано?

2021-12-03 09:27 UTC, gorbunovav commented on components/organisms/o-forevers-creation-wizard.vue
> +  },
@soarer1004 похоже забыл убрать

2021-12-03 09:27 UTC, gorbunovav commented on components/organisms/o-order-confirmation.vue
> +  },
и тут

2021-12-03 09:37 UTC, soarer1004 commented on components/organisms/o-forevers-creation-wizard.vue
> +  },
@gorbunovav Запушил правки

2021-12-06 11:47 UTC, gorbunovav approved these changes

2021-12-06 11:47 UTC, merged