#24378 Products description
BudsiesApp/vsf-capybara pull request #56
Opened 2021-11-26 15:49 UTC by soarer1004

2021-11-27 13:39 UTC, gorbunovav requested changes

2021-11-27 13:39 UTC, gorbunovav commented on pages/Product.vue
> +    </div>
Наверное это можно реализовать отдельным компонентом, чтобы не дублировать работу со Storyblok в нескольких местах.

Fallback в виде контента из description наверное можно оставить - я там создал задачу, чтобы description пока не выгружался в Elasticsearch (т.к. мы его выгружаем в Storyblok).

Заголовок думаю имеет смысл оставить только для fallback-варианта - т.к. в Storyblok заголовок можно самим седлать под конкртеный продукт 🤔

И при загрузке историй там кэш используется - соответственно можно по идее сделать предзагрузку в asyncData страниц (история тогда останется в Vuex после загрузки на сервере)

2021-11-27 15:34 UTC, gorbunovav commented on pages/Product.vue
> +    </div>
С применением `serverPrefetch` (https://redmine.optimuspro.ru/issues/25448) можно по идее и загрузку на стороне сервера прямо в этом отедльном компоненте организовать.

2021-11-29 12:51 UTC, gorbunovav requested changes

2021-11-29 12:51 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +      return `${storyParentFolderName}/${this.product.sku}`;
Мне кажется раз мы выделяем отдельный компонент для работы со Storyblok, то логичнее все, что касается Storyblok там внутри и держать.
Сейчас получается, что все компоненты, используеющие наш, должны что то знать о структуре папок в Storyblok.

Как вариант - сделать два компонента с общим миксином - одние для работы с product, другой - с category.
Либо передавать product/category в одном параметре и сделать параметр type для задания типа нужной истории.

2021-11-29 13:08 UTC, gorbunovav commented on components/molecules/m-description-story.vue
> +      <SfHeading :title="$t('Additional Details')" :level="3" />
заголовок выводить не нужно, если контента нет

2021-11-30 06:16 UTC, soarer1004 commented on components/organisms/o-printed-product-order-form.vue
> +      return `${storyParentFolderName}/${this.product.sku}`;
@gorbunovav Сделал 2 компонента и общий код вынес в миксин. С параметром type логика компонента немного запутанная получается.

2021-11-30 06:17 UTC, soarer1004 commented on components/molecules/m-description-story.vue
> +      <SfHeading :title="$t('Additional Details')" :level="3" />
@gorbunovav Как я понял, все описания будут храниться в storyblok, поэтому избавился от кода для фолбэка

2021-11-30 13:58 UTC, gorbunovav approved these changes

2021-11-30 13:59 UTC, merged