#25588: Phrase Pillows - allow to pre-select the design variant through the query parameters
BudsiesApp/vsf-capybara pull request #72
Opened 2021-12-13 06:30 UTC by soarer1004

2021-12-14 16:44 UTC, gorbunovav requested changes

2021-12-14 16:44 UTC, gorbunovav commented on router/index.js
> +  },
Наверное лушче наоборот сделать, чтобы старая url пока осталась.
Потом отдельно тогда замену проведем 🤔

2021-12-14 16:44 UTC, gorbunovav commented on pages/PhrasePillowProduct.vue
> +const loadProduct = async () => {
Нужно подмержить изменения из основной ветки и отталкиваться в плане загрузки от реализации там (если нет противопоказаний).

2021-12-14 16:44 UTC, gorbunovav commented on pages/PhrasePillowProduct.vue
> +      this.$router.push({ params: { parentSku: value } });
а почему тут без параметров? 🤔

2021-12-14 16:44 UTC, gorbunovav commented on components/organisms/o-phrase-pillow-product-order-form.vue
> +    },
Это не логично настолько модифицировать значение в getter'е.
Ты перенес эту логику из метода `selectDefaultBackDesignForFront` - там понятно, по набору правил выбирается новое дефолтное значение при изменении front design.

Тут же computed-свойство - т.е. правила, по котоым постоянно вычисляется значение.
В итоге связь между фактическим состоянием и реузльтирующим значением получается сильно не прозрачной.

2021-12-14 16:44 UTC, gorbunovav commented on pages/PhrasePillowProduct.vue
> +      :initial-front-design="frontDesign"
поскольку значения выбранных дизайнов теперь напрямую транслируются в url при изменении - это видимо больше не "initial", это просто значение.

2021-12-14 16:44 UTC, gorbunovav commented on components/organisms/o-phrase-pillow-product-order-form.vue
> +      this.$emit('front-design-selected', value);
т.к. url содержит одновременно значения и для front и для back - то возможно проще в одном событии сразу оба и передавать (тогда проще реализовать один переход на новое значение url)

2021-12-16 09:37 UTC, gorbunovav commented on router/index.js
> +  },
@soarer1004 под старой я имел ввиду ту, что сейчас в Magento

2021-12-16 09:38 UTC, soarer1004 commented on router/index.js
> +  },
@gorbunovav Извиняюсь, не понял сразу. Сейчас поправлю

2021-12-16 10:46 UTC, gorbunovav requested changes

2021-12-16 10:46 UTC, gorbunovav commented on components/organisms/o-phrase-pillow-product-order-form.vue
> +    selectedBackDesign: {
Давай все же свойства назовем `frontDesign` и `backDesign` - чтобы снаружи компонента это выглядело более согласованно.

А computed свойство назовем тогда как раз `selectedBackDesign`.

И `defaultBackDesign` можно сделать computed - свойством видимо, раз это значение теперь не сохраняется в `backDesign`.

2021-12-17 07:01 UTC, soarer1004 commented on components/organisms/o-phrase-pillow-product-order-form.vue
> +    selectedBackDesign: {
`defaultBackDesign` все же, наверное, не стоит делать computed. Если `defaultBackDesign` будет computed свойством, то оно будет рассчитываться на основании текущего `frontDesign`(который через query передается). И тогда в `onFrontDesignSelect` при вызове `selectDefaultAccentColor` мы не сможем гарантировать, что `selectedBackDesign` рассчитанный на основании computed свойства `defaultBackDesign` будет верным. И соответсвенно не можем гарантировать, что цвет будет выбран корректный

2021-12-17 07:05 UTC, gorbunovav commented on components/organisms/o-phrase-pillow-product-order-form.vue
> +    selectedBackDesign: {
@soarer1004 А почему не сможем гарантировать?

2021-12-17 07:19 UTC, soarer1004 commented on components/organisms/o-phrase-pillow-product-order-form.vue
> +    selectedBackDesign: {
@gorbunovav Т.к. значение входящего параметра обновляется не сразу(Т.к. через роутер). А вызов `selectDefaultAccentColor` происходит сразу после того, как было выброшено событие `design-selected`

2021-12-17 07:34 UTC, gorbunovav commented on components/organisms/o-phrase-pillow-product-order-form.vue
> +    selectedBackDesign: {
@soarer1004 ну кстати мы наверное хотим менять выбранный цвет при смене дизайнов через url (если он не был выбран пользователем явно).
Т.е. возможно логичнее тогда это в watcher'е делать или тоже как computed

2021-12-17 10:51 UTC, gorbunovav approved these changes

2021-12-17 10:51 UTC, merged