#25610: Cart page - CTA button in the header - fix button text
BudsiesApp/vsf-capybara pull request #73
Opened 2021-12-13 07:37 UTC by soarer1004

2021-12-14 17:16 UTC, gorbunovav requested changes

2021-12-14 17:16 UTC, gorbunovav commented on mixins/header-cta-button.ts
> +import HeaderCtaButtonType from 'src/modules/shared/types/header-cta-button-type';
А для чего нам константы размещать в репозитории приложения, если они используются в одном месте в теме? 🤔

Ну т.е. до этого у нас был случай, когда константы нужно было исопльзовать и в теме и в модуле приложения. А тут же не так.

2021-12-14 17:16 UTC, gorbunovav commented on mixins/header-cta-button.ts
> +export default Vue.extend({
а для чего нам именно mixin? возможно проще сделать просто компонент? (все равно тут логика для обеих кнопок)

2021-12-15 03:32 UTC, soarer1004 commented on mixins/header-cta-button.ts
> +import HeaderCtaButtonType from 'src/modules/shared/types/header-cta-button-type';
@gorbunovav На Budsies, получается, логика такая-же. Т.е. при добвалении новой темы мы сможем использовать эти же типы. Если разместим в теме - придётся переносить/копипастить. От этого отталкивался

2021-12-15 03:39 UTC, soarer1004 commented on mixins/header-cta-button.ts
> +export default Vue.extend({
@gorbunovav Наверное, тут лучше вынести миксин из темы и сделать отдельный компонент для двух кнопок? Чтобы при реализации темы для Budsies, использовать этот миксин

2021-12-15 07:43 UTC, gorbunovav commented on mixins/header-cta-button.ts
> +import HeaderCtaButtonType from 'src/modules/shared/types/header-cta-button-type';
@soarer1004 мы ещё не решили как будем реализовывать тему для Budsies, так что я думаю это преждевременная оптимизация пока 🤔 (тоже касается миксина)

2021-12-15 07:44 UTC, soarer1004 commented on mixins/header-cta-button.ts
> +import HeaderCtaButtonType from 'src/modules/shared/types/header-cta-button-type';
@gorbunovav Хорошо

2021-12-15 09:41 UTC, gorbunovav approved these changes

2021-12-15 09:41 UTC, merged