#24549: Tweak urls to match the old website
BudsiesApp/vsf-capybara pull request #89
Opened 2021-12-24 06:32 UTC by soarer1004

2021-12-24 23:08 UTC, gorbunovav requested changes

2021-12-24 23:08 UTC, gorbunovav commented on config/modules.ts
> +      const productResult = await mappingFallbackForProduct(context, payload);
по идее если история нашлась, то нет смысла искать продукт 🤔

2021-12-24 23:08 UTC, gorbunovav commented on config/modules.ts
> +  registerModule(PaymentBackendMethodsModule)
а это в связи с чем добаилось?

2021-12-24 23:08 UTC, gorbunovav commented on router/index.js
> +    path: '/forevers/create/:productId?',
А для чего нам product id в этом маршруте? 

вроде же в Magento-вариантах такого нет и для старых url мы решили сделать редирект на новую.

Внутри страницы этот параметр не используется.

2021-12-24 23:08 UTC, gorbunovav commented on router/index.js
> +    path: '/plushie/index/create/id/12/type/pillow',
12 - это `plushieId` в старом роуте

2021-12-24 23:08 UTC, gorbunovav commented on pages/Checkout.vue
> +      if (!isServer && !this.showThankYouPage) {
насколько вижу - добавился просто выход по еще одному условию - можно наверное что то такое использовать, чтобы весь код не дублировать:
https://forum.vuejs.org/t/call-the-overrided-method-from-extend-mixin-think-super/1469

2021-12-24 23:08 UTC, gorbunovav commented on config/modules.ts
> +      const productResult = await mappingFallbackForProduct(context, payload);
И нам получается нужно заменить тогда ссылки на странцы продуктов везде чтобы без префикса 'p' было 🤔 

Т.к. сейчас проиндексированы они, Magento в карту сайт будет их отдавать, а когда одна и таже страница доступна по двум url - это плохо для SEO.

2021-12-28 05:51 UTC, soarer1004 commented on config/modules.ts
> +  registerModule(PaymentBackendMethodsModule)
Без регистрации этого модуля не работает оформление заказа при выборе пункта "No Payment Information Required" (Например после использования подарочной карты).

2022-01-27 12:23 UTC, gorbunovav approved these changes

2022-01-27 12:23 UTC, merged