24428 masks creation page
BudsiesApp/vsf-capybara pull request #9
Opened 2021-06-01 09:48 UTC by d-kochnov-optimus

2021-06-09 13:30 UTC, gorbunovav requested changes

2021-06-09 13:30 UTC, gorbunovav commented on pages/PrintedProduct.vue
> +      initial-style-value="simplePrintedKeychains"
🤔 (initial-style-value)

2021-06-09 13:30 UTC, gorbunovav commented on pages/PrintedProduct.vue
> +        throw new Error('The printed product has no available styles');
может быть просто пустой массив возвращать?

2021-06-09 13:30 UTC, gorbunovav commented on pages/PrintedProduct.vue
> +      const addons = this.$store.getters['budsies/getPrintedProductAddons'](this.getCurrentProduct.id);
такой синтаксис потому что getter с параметром вызывать нужно? 🤔

2021-06-09 13:30 UTC, gorbunovav commented on pages/PrintedProduct.vue
> +      product-type="23"
наверное можно через computed-свойство возвращать и задать Enum какой нибудь 🤔

2021-06-09 13:30 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +        );
можем заменить вывод уведомления на переход на страницу корзины? 🤔

2021-06-10 08:03 UTC, d-kochnov-optimus commented on pages/PrintedProduct.vue
> +      const addons = this.$store.getters['budsies/getPrintedProductAddons'](this.getCurrentProduct.id);
да, такой же синтаксис используется и в самом VSF

2021-06-10 21:52 UTC, gorbunovav approved these changes

2021-06-10 21:53 UTC, merged