25519: Printed products - implement the "edit" feature
BudsiesApp/vsf-capybara pull request #98
Opened 2022-01-19 11:50 UTC by soarer1004

2022-01-21 12:13 UTC, gorbunovav requested changes

2022-01-21 12:13 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +    existingProduct: {
по идее это cartItem, а не product.
Мы это уже в случае с Forevers обсуждали 🤔

2022-01-21 12:13 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +      return !this.existingProduct || this.hasExtraFaceAddons;
а почему если нет existingProduct, то нужно показывать? 🤔

2022-01-21 12:13 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +        return;
Вроде как метод заполняет данные на базе cartItem - по идее, если у cartItem нет картинок, то локальные поля все равно должны быть заполнены (видимо пустым значением).

В других местах аналогично.

И кстати в Forevers тоже 🤔

2022-01-21 12:13 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +      }
возможно это exception? (вроде как нет смысла передавать undefined, если метод при этом ничего не делает)

2022-01-21 12:13 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +      }
по идее это exception, т.к. такого быть в номральной ситуации не должно

2022-01-21 12:13 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +      this.updateClientAndServerItem({
Тут по идее await должен быть, иначе у тебя метод завершается до завершения этого promise.

Вообще я за синтаксис с async .. await, если нет какой то необходимости в обратном - он более линейный.

2022-01-21 12:13 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +    },
а `fillExistingProductData` тут можем вызывать?

2022-01-21 12:13 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +    fillExistingProductData (existingProduct: CartItem | undefined): void {
тут кстати тоже - навзание тогда должно быть что то про fill from cart item

2022-01-24 07:08 UTC, soarer1004 commented on components/organisms/o-printed-product-order-form.vue
> +      return !this.existingProduct || this.hasExtraFaceAddons;
@gorbunovav Этот флаг нужен только для того, чтобы корректно заполнялись начальные значения(выбранный addon и загруженные изображения) существующего айтема в корзине для компонента `MExtraFaces`. Т.е. если existingProduct нет - то этот флаг должен быть true.

2022-01-24 07:10 UTC, soarer1004 commented on components/organisms/o-printed-product-order-form.vue
> +        return;
@gorbunovav Для Forevers это отдельной задачей пофиксить?

2022-01-24 08:21 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +        return;
@soarer1004 можно в этой же, если там немного 🤔

2022-01-24 08:26 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +      return !this.existingProduct || this.hasExtraFaceAddons;
>Этот флаг нужен только для того, чтобы корректно заполнялись начальные значения(выбранный addon и загруженные изображения) существующего айтема в корзине для компонента MExtraFaces. 

@soarer1004 а можешь тут подробнее пояснить какая логика работы и какую проблему решаем?

2022-01-24 08:45 UTC, soarer1004 commented on components/organisms/o-printed-product-order-form.vue
> +      return !this.existingProduct || this.hasExtraFaceAddons;
@gorbunovav Получается, что начальные значения заполняются в `created` хуке компонента `MExtraFaces`. При первичной отрисовке страницы могут еще быть не подгруженны `addons` и тогда при создании компонента `MExtraFaces` начальные данные не заполнятся. Т.е. этот компонент должен создаться после загрузки аддонов. Но это не распространяется на случаи когда нет `existingCartItem`.

Возможно будет лучше и понятнее добавить в компонент `MExtraFaces` метод `updateInitialValues` и вызывать его в нужный момент в родительском компоненте, а от этого computed свойства избавиться?

2022-01-24 09:18 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +      return !this.existingProduct || this.hasExtraFaceAddons;
> Но это не распространяется на случаи когда нет existingCartItem.

@soarer1004 а почему только на эти случаи? может просто всегда его показывать после загрузки аддонов?

2022-01-24 09:56 UTC, soarer1004 commented on components/organisms/o-printed-product-order-form.vue
> +      return !this.existingProduct || this.hasExtraFaceAddons;
@gorbunovav  Думаю что да, можно показывать всегда после загрузки аддонов. Т.к. особого смысла нет в данном случае использовать `v-show` вместо `v-if`. Тогда уберу дополнительную обёртку с условием и заменю `v-show` на `v-if`.

2022-01-24 09:58 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +      return !this.existingProduct || this.hasExtraFaceAddons;
@soarer1004 ок!

2022-01-24 11:04 UTC, gorbunovav commented on components/organisms/o-printed-product-order-form.vue
> +          this.$store.dispatch('cart/addItem', {
@soarer1004 await'а не хватает

2022-01-24 11:07 UTC, soarer1004 commented on components/organisms/o-printed-product-order-form.vue
> +          this.$store.dispatch('cart/addItem', {
@gorbunovav Исправил

2022-01-24 11:13 UTC, gorbunovav approved these changes

2022-01-24 11:13 UTC, merged